# Generated by Django 4.1.2 on 2023-04-28 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='followed_games',
            field=models.JSONField(default=dict),
        ),
    ]
