# Generated by Django 4.1.2 on 2022-12-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='supported_languages',
            field=models.TextField(default='Languages'),
        ),
    ]
