# Generated by Django 4.1.2 on 2023-01-17 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='genres',
            field=models.JSONField(default=dict),
        ),
    ]
