# Generated by Django 4.1.2 on 2022-12-05 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_game_supported_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='app_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.game'),
        ),
    ]
