# Generated by Django 4.1.2 on 2023-01-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_game_genres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='app',
            new_name='app_id',
        ),
        migrations.AlterField(
            model_name='review',
            name='language',
            field=models.CharField(default='', max_length=50),
        ),
    ]
