# Generated by Django 4.1.2 on 2023-01-17 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_review_playtime_at_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='author',
            new_name='author_id',
        ),
        migrations.RemoveField(
            model_name='review',
            name='time_updated',
        ),
    ]
