# Generated by Django 4.1.2 on 2023-01-17 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_app_review_app_id_alter_review_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='review_id',
            field=models.IntegerField(default=0),
        ),
    ]
