# Generated by Django 4.1.2 on 2023-01-17 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_author_review_author_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='author_id',
            field=models.IntegerField(default=0),
        ),
    ]
