# Generated by Django 4.1.2 on 2022-12-06 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_review_time_created_alter_review_time_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='app_id',
            new_name='app',
        ),
        migrations.CreateModel(
            name='ReviewData',
            fields=[
                ('review_data_id', models.IntegerField(default=0, primary_key=True, serialize=False, unique=True)),
                ('sentiment', models.JSONField(default=[{'label': '-1', 'value': 0}, {'label': '-0.9', 'value': 0}, {'label': '-0.8', 'value': 0}, {'label': '-0.7', 'value': 0}, {'label': '-0.6', 'value': 0}, {'label': '-0.5', 'value': 0}, {'label': '-0.4', 'value': 0}, {'label': '-0.3', 'value': 0}, {'label': '-0.2', 'value': 0}, {'label': '-0.1', 'value': 0}, {'label': '0', 'value': 0}, {'label': '0.1', 'value': 0}, {'label': '0.2', 'value': 0}, {'label': '0.3', 'value': 0}, {'label': '0.4', 'value': 0}, {'label': '0.5', 'value': 0}, {'label': '0.6', 'value': 0}, {'label': '0.7', 'value': 0}, {'label': '0.8', 'value': 0}, {'label': '0.9', 'value': 0}, {'label': '1', 'value': 0}])),
                ('app', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.game')),
            ],
        ),
    ]
