# Generated by Django 4.1.2 on 2023-01-17 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_review_id_alter_review_review_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_id',
            field=models.IntegerField(),
        ),
    ]
