# Generated by Django 4.1.2 on 2023-01-17 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_review_author_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='playtime_at_review',
            field=models.IntegerField(default=-1),
        ),
    ]
