# Generated by Django 4.1.2 on 2022-12-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_app_id_review_app_reviewdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewdata',
            name='sentiment',
            field=models.JSONField(default={'label': 'value'}),
        ),
    ]
