# Generated by Django 4.1.2 on 2023-01-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_review_playtime_at_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='author_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
