# Generated by Django 4.1.2 on 2022-12-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_reviewdata_sentiment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewdata',
            name='sentiment',
            field=models.JSONField(default=dict),
        ),
    ]
