# Generated by Django 4.1.2 on 2022-12-06 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_reviewdata_sentiment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReviewData',
            new_name='ReviewsStat',
        ),
    ]
