# Generated by Django 4.1.2 on 2023-01-25 14:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_review_app_id_gamestat'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_count', models.IntegerField(default=-1)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('app_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.game')),
            ],
        ),
    ]
