# Generated by Django 4.1.2 on 2022-12-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_reviewsstat_sentiment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewsstat',
            name='sentiment',
            field=models.JSONField(default=dict),
        ),
    ]
