# Generated by Django 4.1.2 on 2022-12-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_reviewsstat_sentiment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewsstat',
            name='review_data_id',
        ),
        migrations.AddField(
            model_name='reviewsstat',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
