# Generated by Django 4.1.2 on 2022-12-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_reviewsstat_review_data_id_reviewsstat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewsstat',
            name='emotion',
            field=models.JSONField(default=dict),
        ),
    ]
