# Generated by Django 4.1.2 on 2023-01-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_gamestat_highest_player_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='playtime_at_review',
            field=models.BigIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='review',
            name='votes_funny',
            field=models.BigIntegerField(default=0),
        ),
    ]
