# Generated by Django 4.1.2 on 2023-01-31 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_review_playtime_at_review_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descriptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='', max_length=20)),
                ('name', models.CharField(default='', max_length=100)),
                ('symbol', models.CharField(default='bi-asterisk', max_length=100)),
            ],
        ),
    ]
