# Generated by Django 4.1.2 on 2023-01-17 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_reviewsstat_emotion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewsStat',
        ),
    ]
