# Generated by Django 4.1.2 on 2023-02-12 18:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_game_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestat',
            name='current_sentiment_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='gamestat',
            name='highest_player_count_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='gamestat',
            name='highest_review_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamestat',
            name='highest_sentiment_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='gamestat',
            name='highest_sentiment_score_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
