# Generated by Django 4.1.2 on 2023-02-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_developer'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='linux_support',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='mac_support',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='windows_support',
            field=models.BooleanField(default=False),
        ),
    ]
