# Generated by Django 4.1.2 on 2023-02-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_game_linux_support_game_mac_support_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='linux_requirements',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='game',
            name='mac_requirements',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='game',
            name='windows_requirements',
            field=models.JSONField(default=dict),
        ),
    ]
