# Generated by Django 4.1.2 on 2023-02-13 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_game_linux_requirements_game_mac_requirements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
