# Generated by Django 4.1.2 on 2023-02-16 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_game_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestat',
            name='reviews_all_time_year',
            field=models.JSONField(default=dict),
        ),
    ]
