# Generated by Django 4.1.2 on 2023-02-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_gamestat_reviews_all_time_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestat',
            name='reviews_all_time_month',
            field=models.JSONField(default=dict),
        ),
    ]
