# Generated by Django 4.1.2 on 2023-02-20 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_gamestat_reviews_all_time_month'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamestat',
            old_name='emotion',
            new_name='emotion_all_time',
        ),
        migrations.RenameField(
            model_name='gamestat',
            old_name='sentiment',
            new_name='sentiment_all_time',
        ),
    ]
