# Generated by Django 4.1.2 on 2023-02-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_gamestat_reviews_past_one_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestat',
            name='sentiment_all_time_month',
            field=models.JSONField(default=dict),
        ),
    ]
