# Generated by Django 4.1.2 on 2023-02-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_gamestat_sentiment_past_one_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestat',
            name='sentiment_past_one_week',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='gamestat',
            name='sentiment_past_two_weeks',
            field=models.JSONField(default=dict),
        ),
    ]
