# Generated by Django 4.1.2 on 2023-02-25 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_gamestat_sentiment_past_one_week_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestat',
            name='emotion_all_time_month',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='gamestat',
            name='emotion_past_one_month',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='gamestat',
            name='emotion_past_one_week',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='gamestat',
            name='emotion_past_two_weeks',
            field=models.JSONField(default=dict),
        ),
    ]
