# Generated by Django 4.1.2 on 2023-02-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_gamestat_current_review_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestat',
            name='highest_review_score',
            field=models.FloatField(default=0.0),
        ),
    ]
