# Generated by Django 4.1.2 on 2023-04-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_developer_common_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestat',
            name='number_of_reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamestat',
            name='number_reviews_negative',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamestat',
            name='number_reviews_positive',
            field=models.IntegerField(default=0),
        ),
    ]
